### ISSUE TITLE
Improving design

### ISSUE THREAD

**Issue by dikac** [daunt/tissue#1]
https://github.com/daunt/tissue/blob/fc0522ddfe6db2b2557031d80ac609a72b9c991e/backend/modules/core/modules/hospital/controllers/BaseController.php#L23-L74

Memberi Dokumentasi pada public API, agar maksud dan definisi type menjadi jelas;

Snippet di bawah tidak ada deskripsi dan type
```
 public $modelClass;
```
menjadi
```
/**
 * description
 * @var type
 */
 public $modelClass;
```

Untuk lebih aman dengan getter setter (Sebelum [Typed Property](https://wiki.php.net/rfc/typed_properties_v2) )

```
private  $modelClass;

public function setModelClass(type $model) : void 
{
    $this->modelClass = $model;
}

public function getModelClass() : type
{
    return $this->modelClass;
}
```

**Comment by daunt** [comment]
mantappp
